### ISSUE TITLE
could you provide a docker image?

### ISSUE THREAD

**Issue by SZTU-Courses** [LINs-lab/FedTHE#2]
I have bullied many times dockerfile provided, but still remain many problems, could you provide an official image for this project?

**Comment by tlin-taolin** [comment]
thank you for your comment! we are working on it.

**Comment by LiangzeJiang** [comment]
Hi,

We have added an image to a public repo, please check https://github.com/LINs-lab/FedTHE#requirements for more details.

Feel free to let us know if you have further questions :)

**Comment by SZTU-Courses** [comment]
> Hi,
> 
> We have added an image to a public repo, please check https://github.com/LINs-lab/FedTHE#requirements for more details.
> 
> Feel free to let us know if you have further questions :)

Got it, Thanks!
