### ISSUE TITLE
TTA

### ISSUE THREAD

**Issue by cht619** [LINs-lab/FedTHE#3]
如果我想直接关注TTA，看哪个部分？get_worker_class好像没有在master中调用，不知道TTA的流程是啥

**Comment by LiangzeJiang** [comment]
Hi, thank you for your interest in our work! For the Test-time Head Ensemble (THE) part, you could take a look at
https://github.com/LINs-lab/FedTHE/blob/master/pcode/local_training/THE_worker.py
which contains all you might want to know about the process of test-time adaptation (TTA), please let us know if you have further questions.
