### ISSUE TITLE
world and world_conf settings

### ISSUE THREAD

**Issue by wenxinyang1026** [LINs-lab/FedTHE#4]
Thanks for your excellent work!
I have pulled the provided image, but when I ran the main.py, I got the error "you should at least make sure world or world_conf is not None.", because the default values of world and world_conf are None. So may I ask how do I set the hyperparameters when running main.py ? Thanks!

**Comment by tlin-taolin** [comment]
hello, you may find the configuration here `https://github.com/LINs-lab/FedTHE/tree/master/exps`.
